### ISSUE TITLE
[Windows] Program removes backslashes in path when calling subprocess

### ISSUE THREAD

**Issue by CenTdemeern1** [bootphon/phonemizer#17]
```
Traceback (most recent call last):
  File "c:\users\User\appdata\local\programs\python\python36-32\lib\site-packages\phonemizer\festival.py", line 140, in _process
    shlex.split(cmd), stderr=fstderr)
  File "c:\users\User\appdata\local\programs\python\python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\users\User\appdata\local\programs\python\python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['festival', '-b', 'C:UsersUserAppDataLocalTemptmph1yalspd']' returned non-zero exit status 4294967295.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\Scripts\phonemize-script.py", line 11, in <module>
    load_entry_point('phonemizer==0.3.1', 'console_scripts', 'phonemize')()
  File "c:\users\User\appdata\local\programs\python\python36-32\lib\site-packages\phonemizer\main.py", line 192, in main
    separator=sep, strip=args.strip, njobs=args.njobs, logger=logger)
  File "c:\users\User\appdata\local\programs\python\python36-32\lib\site-packages\phonemizer\phonemize.py", line 113, in phonemize
    separator=separator, strip=strip)
  File "c:\users\User\appdata\local\programs\python\python36-32\lib\site-packages\phonemizer\festival.py", line 77, in phonemize
    b = _process(a, script, logger)
  File "c:\users\User\appdata\local\programs\python\python36-32\lib\site-packages\phonemizer\festival.py", line 149, in _process
    .format(cmd, err.returncode, fstderr.read()))
RuntimeError: Command "festival -b C:\Users\User\AppData\Local\Temp\tmph1yalspd" returned exit status 4294967295, output is:
SIOD ERROR: could not open file C:UsersUserAppDataLocalTemptmph1yalspd
```

So I think I know what happend:
in the module phonemizer.espeak at line 85 it calls shlex.split(command). when testing, this happend:

```
>>> command='C:\\Users\\User\\AppData\\Local\\Temp\\test'
>>> shlex.split(command)
['C:UsersUserAppDataLocalTemptest']
```

This has something to do with Windows paths using backslashes.

This can be proven by replacing the double backslashes with forwardslashes.

Then the path returned keeps its path seperators (forwardslashes).

**Comment by mmmaat** [comment]
Thank you for reporting. I never tested it on Windows but was thinking shlex is generic enough... This is related to the `posix` option of shlex.split I guess:
```
>>> command='festival -b C:\\Users\\User\\AppData\\Local\\Temp\\test'
>>> shlex.split(command, posix=False)
['festival', '-b', 'C:\\Users\\User\\AppData\\Local\\Temp\\test']
>>> shlex.split(command, posix=True)
['festival', '-b', 'C:UsersUserAppDataLocalTemptest']
```

I'll push a bugfix in few hours and let you know!

**Comment by mmmaat** [comment]
I fixed it, should be OK now...
