### ISSUE TITLE
No module named 'segments'

### ISSUE THREAD

**Issue by t-duan** [bootphon/phonemizer#52]
Hi, I tried to install Phonemizer from sources, when I run "python setup.py", I got the following error: 
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import phonemizer
  File "/home/duan/phonemizer/phonemizer/__init__.py", line 17, in <module>
    from .phonemize import phonemize
  File "/home/duan/phonemizer/phonemizer/phonemize.py", line 27, in <module>
    from phonemizer.backend import (
  File "/home/duan/phonemizer/phonemizer/backend/__init__.py", line 19, in <module>
    from .segments import SegmentsBackend
  File "/home/duan/phonemizer/phonemizer/backend/segments.py", line 20, in <module>
    import segments
ModuleNotFoundError: No module named 'segments'

**Comment by mmmaat** [comment]
Hi, thanks for reporting. I guess this is due to a recent change in the import system (https://github.com/bootphon/phonemizer/blob/master/CHANGELOG.md#phonemizer-221), I'll fix it soon.

If you can't wait, just edit `setup.py`: remove the line `import phonemizer` and change the line `version=phonemizer.__version__` to `version='2.2.1'`.

**Comment by t-duan** [comment]
Ok, thank you very much!
