### ISSUE TITLE
Encoding error README in setup

### ISSUE THREAD

**Issue by isn0gud** [bootphon/phonemizer#8]
```Dockerfile
FROM nvidia/cuda:8.0-cudnn7-runtime-ubuntu16.04

VOLUME /data

RUN apt-get update && apt-get install -y python3.5 python3-pip git festival espeak

RUN pip3 install -U pip

#install phonemizer
RUN  git clone https://github.com/bootphon/phonemizer
WORKDIR /phonemizer
RUN python3 setup.py build
```

```
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    long_description=open('README.md').read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 229: ordinal not in range(128)
```

**Comment by mmmaat** [comment]
Solved by #9, thanks!
